#!/bin/sh
[[ $(stat -c "%G" /dev/dri/card0) != "video" ]] && chgrp video /dev/dri/card0
#[[ $(stat -c "%G" /dev/dri/render*) != "render" ]] && chgrp render /dev/dri/render*
gosu kodi /usr/bin/kodi-standalone
